export const METAMASK_NOT_INSTALLED = 'METAMASK_NOT_INSTALLED';
export const CONNECT_FAILED = 'CONNECT_FAILED';
export const SIGN_FAILED = 'SIGN_FAILED';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
